//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for HealthStatus.
const (
	Ok           HealthStatus = "ok"
	ShuttingDown HealthStatus = "shutting_down"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	case ShuttingDown:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotStatus.
const (
	Creating      SnapshotStatus = "creating"
	Deleted       SnapshotStatus = "deleted"
	Deleting      SnapshotStatus = "deleting"
	ErrorDeleting SnapshotStatus = "error_deleting"
	Failed        SnapshotStatus = "failed"
	Pending       SnapshotStatus = "pending"
	Ready         SnapshotStatus = "ready"
)

// Valid indicates whether the value is a known member of the SnapshotStatus enum.
func (e SnapshotStatus) Valid() bool {
	switch e {
	case Creating:
		return true
	case Deleted:
		return true
	case Deleting:
		return true
	case ErrorDeleting:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// CreateSnapshotRequest defines model for CreateSnapshotRequest.
type CreateSnapshotRequest struct {
	Name string `json:"name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// MetricsText Prometheus exposition text. The series are `snapshot_queue_depth`,
// `snapshot_storage_duration_seconds` (`_count` and `_sum`), and
// `snapshot_storage_errors_total`.
type MetricsText = string

// Snapshot defines model for Snapshot.
type Snapshot struct {
	Attempts  int            `json:"attempts"`
	CreatedAt time.Time      `json:"created_at"`
	Error     *string        `json:"error,omitempty"`
	Id        string         `json:"id"`
	Name      string         `json:"name"`
	Status    SnapshotStatus `json:"status"`
	TenantId  string         `json:"tenant_id"`
	UpdatedAt time.Time      `json:"updated_at"`
	VolumeId  string         `json:"volume_id"`
}

// SnapshotList defines model for SnapshotList.
type SnapshotList struct {
	Snapshots []Snapshot `json:"snapshots"`
}

// SnapshotStatus defines model for SnapshotStatus.
type SnapshotStatus string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// SnapshotId defines model for SnapshotId.
type SnapshotId = string

// TenantID defines model for TenantID.
type TenantID = string

// VolumeId defines model for VolumeId.
type VolumeId = string

// Error defines model for Error.
type Error = ErrorResponse

// ListSnapshotsParams defines parameters for ListSnapshots.
type ListSnapshotsParams struct {
	VolumeId  *string         `form:"volume_id,omitempty" json:"volume_id,omitempty"`
	Status    *SnapshotStatus `form:"status,omitempty" json:"status,omitempty"`
	XTenantID TenantID        `json:"X-Tenant-ID"`
}

// DeleteSnapshotParams defines parameters for DeleteSnapshot.
type DeleteSnapshotParams struct {
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// GetSnapshotParams defines parameters for GetSnapshot.
type GetSnapshotParams struct {
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// CreateSnapshotParams defines parameters for CreateSnapshot.
type CreateSnapshotParams struct {
	XTenantID      TenantID        `json:"X-Tenant-ID"`
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// CreateSnapshotJSONRequestBody defines body for CreateSnapshot for application/json ContentType.
type CreateSnapshotJSONRequestBody = CreateSnapshotRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetHealth Liveness probe
	//
	// Corresponds with GET /healthz (the `GetHealth` operationId).
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMetrics Prometheus metrics
	//
	// Prometheus text exposition, version 0.0.4. No `X-Tenant-ID` is required.
	// The scrape stays available while the process is draining, after
	// `GET /healthz` has started answering 503.
	//
	// A storage call cancelled because the process is stopping is omitted.
	// It is not a storage failure, and the snapshot stays `creating` or
	// `deleting`.
	//
	// `snapshot_queue_depth` (gauge)
	// Jobs waiting in the worker queue. A job inside a storage call has
	// already left the queue, and backoff does not occupy a concurrency slot.
	//
	// `snapshot_storage_duration_seconds` (summary)
	// Duration of one storage call, in seconds, excluding exponential backoff.
	// Published as `_count` and `_sum`.
	// Labels: `op` is `create` or `delete`; `result` is `success` or `error`.
	//
	// `snapshot_storage_errors_total` (counter)
	// Storage calls that returned an error, including timeouts that count as
	// a failed attempt. Label: `op` (`create` or `delete`).
	//
	// Corresponds with GET /metrics (the `GetMetrics` operationId).
	GetMetrics(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListSnapshots List the tenant's snapshots
	//
	// Corresponds with GET /v1/snapshots (the `ListSnapshots` operationId).
	ListSnapshots(ctx context.Context, params *ListSnapshotsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteSnapshot Start an asynchronous delete
	//
	// Corresponds with DELETE /v1/snapshots/{id} (the `DeleteSnapshot` operationId).
	DeleteSnapshot(ctx context.Context, id SnapshotId, params *DeleteSnapshotParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSnapshot Fetch one snapshot
	//
	// Corresponds with GET /v1/snapshots/{id} (the `GetSnapshot` operationId).
	GetSnapshot(ctx context.Context, id SnapshotId, params *GetSnapshotParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateSnapshotWithBody Accept a new snapshot
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/volumes/{volumeId}/snapshots (the `CreateSnapshot` operationId).
	CreateSnapshotWithBody(ctx context.Context, volumeId VolumeId, params *CreateSnapshotParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateSnapshot Accept a new snapshot
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/volumes/{volumeId}/snapshots (the `CreateSnapshot` operationId).
	CreateSnapshot(ctx context.Context, volumeId VolumeId, params *CreateSnapshotParams, body CreateSnapshotJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetHealth Liveness probe
//
// Corresponds with GET /healthz (the `GetHealth` operationId).
func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetMetrics Prometheus metrics
//
// Prometheus text exposition, version 0.0.4. No `X-Tenant-ID` is required.
// The scrape stays available while the process is draining, after
// `GET /healthz` has started answering 503.
//
// A storage call cancelled because the process is stopping is omitted.
// It is not a storage failure, and the snapshot stays `creating` or
// `deleting`.
//
// `snapshot_queue_depth` (gauge)
// Jobs waiting in the worker queue. A job inside a storage call has
// already left the queue, and backoff does not occupy a concurrency slot.
//
// `snapshot_storage_duration_seconds` (summary)
// Duration of one storage call, in seconds, excluding exponential backoff.
// Published as `_count` and `_sum`.
// Labels: `op` is `create` or `delete`; `result` is `success` or `error`.
//
// `snapshot_storage_errors_total` (counter)
// Storage calls that returned an error, including timeouts that count as
// a failed attempt. Label: `op` (`create` or `delete`).
//
// Corresponds with GET /metrics (the `GetMetrics` operationId).
func (c *Client) GetMetrics(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMetricsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListSnapshots List the tenant's snapshots
//
// Corresponds with GET /v1/snapshots (the `ListSnapshots` operationId).
func (c *Client) ListSnapshots(ctx context.Context, params *ListSnapshotsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListSnapshotsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteSnapshot Start an asynchronous delete
//
// Corresponds with DELETE /v1/snapshots/{id} (the `DeleteSnapshot` operationId).
func (c *Client) DeleteSnapshot(ctx context.Context, id SnapshotId, params *DeleteSnapshotParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteSnapshotRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetSnapshot Fetch one snapshot
//
// Corresponds with GET /v1/snapshots/{id} (the `GetSnapshot` operationId).
func (c *Client) GetSnapshot(ctx context.Context, id SnapshotId, params *GetSnapshotParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSnapshotRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateSnapshotWithBody Accept a new snapshot
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/volumes/{volumeId}/snapshots (the `CreateSnapshot` operationId).
func (c *Client) CreateSnapshotWithBody(ctx context.Context, volumeId VolumeId, params *CreateSnapshotParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateSnapshotRequestWithBody(c.Server, volumeId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateSnapshot Accept a new snapshot
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/volumes/{volumeId}/snapshots (the `CreateSnapshot` operationId).
func (c *Client) CreateSnapshot(ctx context.Context, volumeId VolumeId, params *CreateSnapshotParams, body CreateSnapshotJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateSnapshotRequest(c.Server, volumeId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetHealthRequest constructs an http.Request for the GetHealth method
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMetricsRequest constructs an http.Request for the GetMetrics method
func NewGetMetricsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/metrics")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListSnapshotsRequest constructs an http.Request for the ListSnapshots method
func NewListSnapshotsRequest(server string, params *ListSnapshotsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/snapshots")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.VolumeId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "volume_id", *params.VolumeId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Status != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "status", *params.Status, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Tenant-ID", params.XTenantID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Tenant-ID", headerParam0)

	}

	return req, nil
}

// NewDeleteSnapshotRequest constructs an http.Request for the DeleteSnapshot method
func NewDeleteSnapshotRequest(server string, id SnapshotId, params *DeleteSnapshotParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/snapshots/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Tenant-ID", params.XTenantID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Tenant-ID", headerParam0)

	}

	return req, nil
}

// NewGetSnapshotRequest constructs an http.Request for the GetSnapshot method
func NewGetSnapshotRequest(server string, id SnapshotId, params *GetSnapshotParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/snapshots/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Tenant-ID", params.XTenantID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Tenant-ID", headerParam0)

	}

	return req, nil
}

// NewCreateSnapshotRequest calls the generic CreateSnapshot builder with application/json body
func NewCreateSnapshotRequest(server string, volumeId VolumeId, params *CreateSnapshotParams, body CreateSnapshotJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateSnapshotRequestWithBody(server, volumeId, params, "application/json", bodyReader)
}

// NewCreateSnapshotRequestWithBody constructs an http.Request for the CreateSnapshot method, with any body, and a specified content type
func NewCreateSnapshotRequestWithBody(server string, volumeId VolumeId, params *CreateSnapshotParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "volumeId", volumeId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/volumes/%s/snapshots", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Tenant-ID", params.XTenantID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Tenant-ID", headerParam0)

		if params.IdempotencyKey != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Idempotency-Key", *params.IdempotencyKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Idempotency-Key", headerParam1)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetHealthWithResponse Liveness probe
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /healthz (the `GetHealth` operationId).
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// GetMetricsWithResponse Prometheus metrics
	//
	// Prometheus text exposition, version 0.0.4. No `X-Tenant-ID` is required.
	// The scrape stays available while the process is draining, after
	// `GET /healthz` has started answering 503.
	//
	// A storage call cancelled because the process is stopping is omitted.
	// It is not a storage failure, and the snapshot stays `creating` or
	// `deleting`.
	//
	// `snapshot_queue_depth` (gauge)
	// Jobs waiting in the worker queue. A job inside a storage call has
	// already left the queue, and backoff does not occupy a concurrency slot.
	//
	// `snapshot_storage_duration_seconds` (summary)
	// Duration of one storage call, in seconds, excluding exponential backoff.
	// Published as `_count` and `_sum`.
	// Labels: `op` is `create` or `delete`; `result` is `success` or `error`.
	//
	// `snapshot_storage_errors_total` (counter)
	// Storage calls that returned an error, including timeouts that count as
	// a failed attempt. Label: `op` (`create` or `delete`).
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /metrics (the `GetMetrics` operationId).
	GetMetricsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMetricsResponse, error)

	// ListSnapshotsWithResponse List the tenant's snapshots
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/snapshots (the `ListSnapshots` operationId).
	ListSnapshotsWithResponse(ctx context.Context, params *ListSnapshotsParams, reqEditors ...RequestEditorFn) (*ListSnapshotsResponse, error)

	// DeleteSnapshotWithResponse Start an asynchronous delete
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /v1/snapshots/{id} (the `DeleteSnapshot` operationId).
	DeleteSnapshotWithResponse(ctx context.Context, id SnapshotId, params *DeleteSnapshotParams, reqEditors ...RequestEditorFn) (*DeleteSnapshotResponse, error)

	// GetSnapshotWithResponse Fetch one snapshot
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/snapshots/{id} (the `GetSnapshot` operationId).
	GetSnapshotWithResponse(ctx context.Context, id SnapshotId, params *GetSnapshotParams, reqEditors ...RequestEditorFn) (*GetSnapshotResponse, error)

	// CreateSnapshotWithBodyWithResponse Accept a new snapshot
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/volumes/{volumeId}/snapshots (the `CreateSnapshot` operationId).
	CreateSnapshotWithBodyWithResponse(ctx context.Context, volumeId VolumeId, params *CreateSnapshotParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateSnapshotResponse, error)

	// CreateSnapshotWithResponse Accept a new snapshot
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/volumes/{volumeId}/snapshots (the `CreateSnapshot` operationId).
	CreateSnapshotWithResponse(ctx context.Context, volumeId VolumeId, params *CreateSnapshotParams, body CreateSnapshotJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateSnapshotResponse, error)
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Health
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Health
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetHealthResponse) GetJSON200() *Health {
	return r.JSON200
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r GetHealthResponse) GetJSON503() *Health {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r GetHealthResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetMetricsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r GetMetricsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetMetricsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMetricsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetMetricsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListSnapshotsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *SnapshotList
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListSnapshotsResponse) GetJSON200() *SnapshotList {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r ListSnapshotsResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetBody returns the raw response body bytes
func (r ListSnapshotsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListSnapshotsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListSnapshotsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListSnapshotsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteSnapshotResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON202 the response for an HTTP 202 `application/json` response
	JSON202 *Snapshot
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON429 the response for an HTTP 429 `application/json` response
	JSON429 *Error
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
}

// GetJSON202 returns the response for an HTTP 202 `application/json` response
func (r DeleteSnapshotResponse) GetJSON202() *Snapshot {
	return r.JSON202
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r DeleteSnapshotResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r DeleteSnapshotResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r DeleteSnapshotResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON429 returns the response for an HTTP 429 `application/json` response
func (r DeleteSnapshotResponse) GetJSON429() *Error {
	return r.JSON429
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r DeleteSnapshotResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r DeleteSnapshotResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteSnapshotResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteSnapshotResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteSnapshotResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetSnapshotResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Snapshot
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetSnapshotResponse) GetJSON200() *Snapshot {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetSnapshotResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetSnapshotResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r GetSnapshotResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetSnapshotResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSnapshotResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetSnapshotResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// CreateSnapshotResponse202Headers the declared response headers of an HTTP 202 response for CreateSnapshot
type CreateSnapshotResponse202Headers struct {
	IdempotencyReplayed *string
}

type CreateSnapshotResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON202 the response for an HTTP 202 `application/json` response
	JSON202 *Snapshot
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON429 the response for an HTTP 429 `application/json` response
	JSON429 *Error
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
	// Headers202 the parsed response headers for an HTTP 202 response
	Headers202 *CreateSnapshotResponse202Headers
}

// GetJSON202 returns the response for an HTTP 202 `application/json` response
func (r CreateSnapshotResponse) GetJSON202() *Snapshot {
	return r.JSON202
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreateSnapshotResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CreateSnapshotResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON429 returns the response for an HTTP 429 `application/json` response
func (r CreateSnapshotResponse) GetJSON429() *Error {
	return r.JSON429
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r CreateSnapshotResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r CreateSnapshotResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateSnapshotResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateSnapshotResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateSnapshotResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetHealthWithResponse Liveness probe
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /healthz (the `GetHealth` operationId).
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// GetMetricsWithResponse Prometheus metrics
//
// Prometheus text exposition, version 0.0.4. No `X-Tenant-ID` is required.
// The scrape stays available while the process is draining, after
// `GET /healthz` has started answering 503.
//
// A storage call cancelled because the process is stopping is omitted.
// It is not a storage failure, and the snapshot stays `creating` or
// `deleting`.
//
// `snapshot_queue_depth` (gauge)
// Jobs waiting in the worker queue. A job inside a storage call has
// already left the queue, and backoff does not occupy a concurrency slot.
//
// `snapshot_storage_duration_seconds` (summary)
// Duration of one storage call, in seconds, excluding exponential backoff.
// Published as `_count` and `_sum`.
// Labels: `op` is `create` or `delete`; `result` is `success` or `error`.
//
// `snapshot_storage_errors_total` (counter)
// Storage calls that returned an error, including timeouts that count as
// a failed attempt. Label: `op` (`create` or `delete`).
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /metrics (the `GetMetrics` operationId).
func (c *ClientWithResponses) GetMetricsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMetricsResponse, error) {
	rsp, err := c.GetMetrics(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMetricsResponse(rsp)
}

// ListSnapshotsWithResponse List the tenant's snapshots
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/snapshots (the `ListSnapshots` operationId).
func (c *ClientWithResponses) ListSnapshotsWithResponse(ctx context.Context, params *ListSnapshotsParams, reqEditors ...RequestEditorFn) (*ListSnapshotsResponse, error) {
	rsp, err := c.ListSnapshots(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListSnapshotsResponse(rsp)
}

// DeleteSnapshotWithResponse Start an asynchronous delete
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /v1/snapshots/{id} (the `DeleteSnapshot` operationId).
func (c *ClientWithResponses) DeleteSnapshotWithResponse(ctx context.Context, id SnapshotId, params *DeleteSnapshotParams, reqEditors ...RequestEditorFn) (*DeleteSnapshotResponse, error) {
	rsp, err := c.DeleteSnapshot(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteSnapshotResponse(rsp)
}

// GetSnapshotWithResponse Fetch one snapshot
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/snapshots/{id} (the `GetSnapshot` operationId).
func (c *ClientWithResponses) GetSnapshotWithResponse(ctx context.Context, id SnapshotId, params *GetSnapshotParams, reqEditors ...RequestEditorFn) (*GetSnapshotResponse, error) {
	rsp, err := c.GetSnapshot(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSnapshotResponse(rsp)
}

// CreateSnapshotWithBodyWithResponse Accept a new snapshot
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/volumes/{volumeId}/snapshots (the `CreateSnapshot` operationId).
func (c *ClientWithResponses) CreateSnapshotWithBodyWithResponse(ctx context.Context, volumeId VolumeId, params *CreateSnapshotParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateSnapshotResponse, error) {
	rsp, err := c.CreateSnapshotWithBody(ctx, volumeId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateSnapshotResponse(rsp)
}

// CreateSnapshotWithResponse Accept a new snapshot
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/volumes/{volumeId}/snapshots (the `CreateSnapshot` operationId).
func (c *ClientWithResponses) CreateSnapshotWithResponse(ctx context.Context, volumeId VolumeId, params *CreateSnapshotParams, body CreateSnapshotJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateSnapshotResponse, error) {
	rsp, err := c.CreateSnapshot(ctx, volumeId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateSnapshotResponse(rsp)
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetMetricsResponse parses an HTTP response from a GetMetricsWithResponse call
func ParseGetMetricsResponse(rsp *http.Response) (*GetMetricsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMetricsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseListSnapshotsResponse parses an HTTP response from a ListSnapshotsWithResponse call
func ParseListSnapshotsResponse(rsp *http.Response) (*ListSnapshotsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListSnapshotsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SnapshotList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseDeleteSnapshotResponse parses an HTTP response from a DeleteSnapshotWithResponse call
func ParseDeleteSnapshotResponse(rsp *http.Response) (*DeleteSnapshotResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteSnapshotResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest Snapshot
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetSnapshotResponse parses an HTTP response from a GetSnapshotWithResponse call
func ParseGetSnapshotResponse(rsp *http.Response) (*GetSnapshotResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSnapshotResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Snapshot
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseCreateSnapshotResponse parses an HTTP response from a CreateSnapshotWithResponse call
func ParseCreateSnapshotResponse(rsp *http.Response) (*CreateSnapshotResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateSnapshotResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest Snapshot
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	switch {
	case rsp.StatusCode == 202:
		var headers CreateSnapshotResponse202Headers
		if values := rsp.Header.Values("Idempotency-Replayed"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Idempotency-Replayed", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.IdempotencyReplayed = &value
		}
		response.Headers202 = &headers
	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Liveness probe
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// GetMetrics Prometheus metrics
	// (GET /metrics)
	GetMetrics(w http.ResponseWriter, r *http.Request)
	// ListSnapshots List the tenant's snapshots
	// (GET /v1/snapshots)
	ListSnapshots(w http.ResponseWriter, r *http.Request, params ListSnapshotsParams)
	// DeleteSnapshot Start an asynchronous delete
	// (DELETE /v1/snapshots/{id})
	DeleteSnapshot(w http.ResponseWriter, r *http.Request, id SnapshotId, params DeleteSnapshotParams)
	// GetSnapshot Fetch one snapshot
	// (GET /v1/snapshots/{id})
	GetSnapshot(w http.ResponseWriter, r *http.Request, id SnapshotId, params GetSnapshotParams)
	// CreateSnapshot Accept a new snapshot
	// (POST /v1/volumes/{volumeId}/snapshots)
	CreateSnapshot(w http.ResponseWriter, r *http.Request, volumeId VolumeId, params CreateSnapshotParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetMetrics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMetrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSnapshots operation middleware
func (siw *ServerInterfaceWrapper) ListSnapshots(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSnapshotsParams

	// ------------- Optional query parameter "volume_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "volume_id", r.URL.Query(), &params.VolumeId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "volume_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "volume_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSnapshots(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSnapshot operation middleware
func (siw *ServerInterfaceWrapper) DeleteSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id SnapshotId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteSnapshotParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSnapshot(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSnapshot operation middleware
func (siw *ServerInterfaceWrapper) GetSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id SnapshotId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSnapshotParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSnapshot(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSnapshot operation middleware
func (siw *ServerInterfaceWrapper) CreateSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "volumeId" -------------
	var volumeId VolumeId

	err = runtime.BindStyledParameterWithOptions("simple", "volumeId", r.PathValue("volumeId"), &volumeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "volumeId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateSnapshotParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSnapshot(w, r, volumeId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/metrics", wrapper.GetMetrics)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/volumes/{volumeId}/snapshots", wrapper.CreateSnapshot)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/snapshots", wrapper.ListSnapshots)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/snapshots/{id}", wrapper.DeleteSnapshot)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/snapshots/{id}", wrapper.GetSnapshot)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFl7b+O4Ef8qA26B7gKK7M3uAq2L+yO9zd2lTYtgExQtTguLkcYWNxKpJakkbuDvXgxJyZItO3Gx9/jL",
	"sjgczuM3D46eWKaqWkmU1rDZE6u55hVa1O7fRY5VrSzKbPV3XNEbIdmMFchz1CxiklfIZn2yE6KLmMkK",
	"rDhtsKuaSIzVQi7Zeh2xa8lrUyh7kXcMa26LDTuRs4hp/NoIjTmbWd3gYY43KLm0Fx/3CvjvE09ycvHx",
	"SNb/UmVT4V5R79vlY7iuidjUShp0Vj7XWml6yJS0KC098rouRcatUHLyxShJ7zYc/6BxwWbs1WTjvIlf",
	"NRPH7VPg70/L0WRa1MSMzdgZkKhoLDxwAxq/YGYxj526gQmd8b1GbrF11ie/xYmW54JY8fJKqxq1FaTG",
	"gpcGI1b3Xj0FKz2xij9eolzags3env4pYpWQ3f9oxOobW/7seXzuqNQtycvWERsqOnvaOhtbqw5fZyrH",
	"EadErEJj+BLHYdAXyHHY0O+KtkXvBRnT4CfkpS12ZTSW28Y9oWwq4qHuKKiKxlohl/NcPcgewz1yBi5j",
	"B/8DrRaZucFH59EhPq60qtAW2BjAx1oZ52yw+GhjuCkQDGqBBrhGSE2Ax/xrgw3Oc6xtkUaJ3CwYqzRf",
	"4jxvtEPz3GCmZG5SeJ3OM9VImwKXOaRz01Tpm4j+jO13VjRzqywv0ziRLNp1YQvWXYtya7GqfYqrhBQV",
	"mXXasRDS4hI18cgc7PM5d1wWSlf0xHJu8cSKCsfO7aAmm7LktyW2OWCHUuSj2GvjZGdhg4RDId/qfe2p",
	"1xGzLt3N9xzX1PnROvpMN85xC3guf28k6O8NqnaKRRvPDEw/kHEMwa3Kl8KMuLtFj/sjLFYvNiFbd4dx",
	"rflqN6o61ofEut6J4BplTsYKavpHjTyncrngokSyTo4lhjX36F46eM27pZHAJ2TJhdqN5TOzklmhlVSN",
	"gU50UAu4F9o2vDypeFYIieB9ZOJEJpKi3DvDhaaXBDJellQvbKMlcANGKfdrC+xYgzDA80pYqiiJPIMH",
	"pe9Qg+XlnQGrPLEPaahLLhGEdC9veXa31KqReQzn96hXoFVjEfAxw9om8sfzG5gULmH+10nlXlQ+kUHw",
	"kBemV+3BdwIxnIEHZCKVLFdgEA0IssSD7NmF+FZ8BYUqc+AWKmUsbQRbcOsynlQ22CMPSUhYinf2iWd3",
	"PyhNZbUFAZxdXRD6URvvjbfxNJ4STFSNkteCzdi7eBq/Y5FrKxxeWh3peYkO24RslzupDWE/og11Y6uN",
	"OJ1Ov1kTEU4Y6R4IG7VWGRrjnJ2Re4RcOk/HpNyH6btfX45ccyFJDAdYhcZ5yksHEh9a8SinNlXF9YrN",
	"2KW4R0kMaq1u0S22iOqZf291pJLYK5ERBE/DNJ7G72P4p4K0h8UURAdUAo+rpZnmNUUEXxng91y48gEP",
	"hSgR7LiKEfCFRZ3ItB8TKRQUk5ZrizlwaR6QkgN8mL5zMX3WhR3FMWRcZliWmMMtZrwxO6cZq+qaGAgD",
	"qgvoCxfhzrQdP0pejUZXuYfJwKuVtgkvBUVSt4ksdXKNtxDwesmbJb5J5N/UrYEHLhzGQq4IScVtoND+",
	"om5BSCNyBD5Us+Amkbx0eRZKXFi332308lLaUYvFBjIqy5p6BRwyJbNGa7rUgCmV3ZL2QF8TAPYmkR/D",
	"IiVcJXEgW0TahE0RpbmyoQLhAEVBIHjZShcn8qq5LYUpyLUGRhqnOJGX/BZLM4NU1Q5q3u5IVgdvdEz/",
	"AqlG05TWU5gmI397Eldm0j1qDtoveO3OR/0mkdc9lYzPk75EOBSC20eqtupRf6EaG0gdH3BOAl8EITQE",
	"MTh9gjqvx5R54zPwTnoM3e3z+ZECeFKXXLiMhI+8ql0ufwU/nV9ewRgy4Vk8JvIV3Pzn6nx8u4N1IkfX",
	"ThO5ffI+lMFhZG3QtEHQtlR7WQf4JvJZUg/DJ1V/l4TmLWGRx9d3CQvgStga3r6EmWmqF7CaxqdHSubR",
	"0mfnQHm8XAcYTePph/3e6wcPvCRgDrhrwCuEYSIPkg2ld1qz6IUFuH9THKnC37sMaWH0zrhdbntEbZV1",
	"Jff+7WTQsI+2PdToX3dU0WBQ9fO4DhuSSTchWkdhjvO1Qb3aHuT4K8qBedD45u4y8zKbbl/X1p9/wU5u",
	"cFHa00f51viPvRtCRD0TGgsLoY11bd376XTfWZ3wfvi002UZX3Z3j9n1/+RJ5GvfdRFcd3Hw0b1vtToa",
	"CL3h4zp6lnoDm10XnX5zF+1zT7h/0bTON7SYH+0Ron5/FPWfj6E+PYY6XBCOR9K15dpSkuT9a21Ayjra",
	"e1/6HaBl+quhpQ2lXxgiA8f8gDYrfB+ykc5HdpgrTJ7aUfl6mOxrZUacNhw+H+23bmp/lNeep936HuL9",
	"7Abjf1X56pu5eHz0vh6OoqxucP0bZqXultfPSxH151yC2BgK7nAFGuuSr0KH8yiM656VxJhF4WPN9vem",
	"k09hy9gVHA1KCw8F+v576/sTVNxmRTiM61Kgbj95xIMi3c7myJSjY7X/I4J+h2nzzE9BuJuDmIFbDer7",
	"NqYaXbIZm7D15/X/BgA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
